---
abstract: 'get search and get a recipe from Yummly'
author:
  - 'Dave Hodgkinson <davehodg@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Yummly
requires:
  HTML::TreeBuilder: '0'
  Pod::Coverage: '0'
  Test::More: '0'
  Test::Pod: '0'
  Test::Pod::Coverage: '0'
  URL::Encode: '0'
  WebService::Simple: '0'
version: '0.4'
